//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_VisualStudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valoracion
    {
        public int ID { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<int> Valorado_ID { get; set; }
        public Nullable<int> Valorador_ID { get; set; }
    
        public virtual UsuarioMobil UsuarioMobil { get; set; }
        public virtual UsuarioMobil UsuarioMobil1 { get; set; }
    }
}
